packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.7'
  - '@turbo/darwin-arm64@2.11.7'
  - '@turbo/linux-64@2.11.7'
  - '@turbo/linux-arm64@2.11.7'
  - '@turbo/windows-64@2.11.7'
  - '@turbo/windows-arm64@2.11.7'
  - '@types/node@24.19.1'
  - nestjs-pino@5.3.0
  - pino@10.4.0
  - supertest@7.3.1
  - turbo@2.11.7
